### ISSUE TITLE
Additional chain support guide

### ISSUE THREAD

**Issue by olifur** [DePayFi/web3-mock#20]
Hi,

Thank you very much for your fast help and eagerness with my other two tickets, I really appreciate it!

I am currently writing a Dapp for the Avax (Avalanche) Mainnet and testing it on their testnet. 

Avax is a EVM compatible blockchain.

Basic tests all worked with the ethereum provider mock of this beautiful library.

Now I am writing more specific UI tests to check if a user connected his wallet on the right chain, so I need avalanche support in the mock providers.

Can you help me or give me some guidelines how I could extend your library to fit my needs. 

I think this would be a great help for other users as well, with the evergrowing number of blockchains all the time.

Best,
Oliver

**Comment by spape** [comment]
Hi Oliver

Thanks for reaching out and thanks for your interest. Glad that it finally worked for you on the new version.

Here are the steps in order to add at least the basic mock support for avalanche:

1. Add Avalanche to web3-blockchains: 
https://github.com/DePayFi/web3-blockchains <https://github.com/DePayFi/web3-blockchains>

2. Add Avalanche to web3-constants:
https://github.com/DePayFi/web3-constants <https://github.com/DePayFi/web3-constants>

3. Add it to the list of supported blockchains in web3-mock here:
https://github.com/DePayFi/web3-mock/blob/main/src/blockchains.js <https://github.com/DePayFi/web3-mock/blob/main/src/blockchains.js>


1+2 should mainly just passing configurations (no actually coding required) except maybe copying some basic tests.

Looking forward

Best
Sebastian

**Comment by olifur** [comment]
Hi Sebastian,

I have implemented changes in the 3 repos by forking them.

https://github.com/DePayFi/web3-blockchains/compare/master...olifur:web3-blockchains:add-avax-providers
https://github.com/DePayFi/web3-constants/compare/master...olifur:web3-constants:add-avax-providers
https://github.com/DePayFi/web3-mock/compare/main...olifur:web3-mock:add-avax-providers

But my new provider `avax_testnet` or `avax` does not work though.

I have a test where I click on a connect button on my site, a modal opens and I click on Metamask.
```
await page.locator('text=Connect Wallet').click()
await page.locator('text=Metamask').waitFor()
await page.locator('text=Metamask').click()
```
If I use `ethereum` as the provider it works fine. But when I use my new `avax_testnet` provider, the modal does not close so there is something wrong with the provider.


Is there any location I am missing?

Best,
Oliver

**Comment by spape** [comment]
Hi Oliver

Sorry I’ve missed the client/provider:

https://github.com/DePayFi/web3-client <https://github.com/DePayFi/web3-client>

https://github.com/DePayFi/web3-client/blob/master/src/blockchains.js <https://github.com/DePayFi/web3-client/blob/master/src/blockchains.js>

https://github.com/DePayFi/web3-client/tree/master/src/blockchains <https://github.com/DePayFi/web3-client/tree/master/src/blockchains>

btw. test nets are generally not supported by depay (because the entire stack can’t be reproduced on testnets).

Best
Sebastian

**Comment by spape** [comment]
Hence we would also not merge a testnet addition/PR.

**Comment by olifur** [comment]
Hey Sebastian, Ok, I will clean the `avax_testnet` before I do a PR.

Meanwhile its still not working, I added it to the web3-client as suggested by you

https://github.com/DePayFi/web3-client/compare/master...olifur:web3-client:add-avax-providers?expand=1

**Comment by spape** [comment]
You would actually need to add it here too: https://github.com/DePayFi/web3-client/tree/master/src/blockchains

**Comment by spape** [comment]
You could just copy paste the bsc directory there just make sure you enter an AVAX RPC endpoint here https://github.com/DePayFi/web3-client/blob/master/src/blockchains/bsc/provider.js
